/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEnriquecimentoRouteImport } from './routes/_authenticated/enriquecimento'
import { Route as AuthenticatedEsteiraRouteImport } from './routes/_authenticated/esteira'
import { Route as AuthenticatedIdeiasRouteImport } from './routes/_authenticated/ideias'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPriorizacaoRouteImport } from './routes/_authenticated/priorizacao'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedTrocarSenhaRouteImport } from './routes/_authenticated/trocar-senha'
import { Route as AuthenticatedVisaoIndicadoresRouteImport } from './routes/_authenticated/visao-indicadores'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminPaginasRouteImport } from './routes/_authenticated/admin.paginas'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedBacklogIndexRouteImport } from './routes/_authenticated/backlog.index'
import { Route as AuthenticatedBacklogIdRouteImport } from './routes/_authenticated/backlog.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnriquecimentoRoute =
  AuthenticatedEnriquecimentoRouteImport.update({
    id: '/enriquecimento',
    path: '/enriquecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEsteiraRoute = AuthenticatedEsteiraRouteImport.update({
  id: '/esteira',
  path: '/esteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdeiasRoute = AuthenticatedIdeiasRouteImport.update({
  id: '/ideias',
  path: '/ideias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPriorizacaoRoute =
  AuthenticatedPriorizacaoRouteImport.update({
    id: '/priorizacao',
    path: '/priorizacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrocarSenhaRoute =
  AuthenticatedTrocarSenhaRouteImport.update({
    id: '/trocar-senha',
    path: '/trocar-senha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisaoIndicadoresRoute =
  AuthenticatedVisaoIndicadoresRouteImport.update({
    id: '/visao-indicadores',
    path: '/visao-indicadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPaginasRoute =
  AuthenticatedAdminPaginasRouteImport.update({
    id: '/paginas',
    path: '/paginas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBacklogIndexRoute =
  AuthenticatedBacklogIndexRouteImport.update({
    id: '/backlog/',
    path: '/backlog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBacklogIdRoute = AuthenticatedBacklogIdRouteImport.update({
  id: '/backlog/$id',
  path: '/backlog/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enriquecimento': typeof AuthenticatedEnriquecimentoRoute
  '/esteira': typeof AuthenticatedEsteiraRoute
  '/ideias': typeof AuthenticatedIdeiasRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/priorizacao': typeof AuthenticatedPriorizacaoRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/visao-indicadores': typeof AuthenticatedVisaoIndicadoresRoute
  '/admin/paginas': typeof AuthenticatedAdminPaginasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/backlog/$id': typeof AuthenticatedBacklogIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/backlog/': typeof AuthenticatedBacklogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enriquecimento': typeof AuthenticatedEnriquecimentoRoute
  '/esteira': typeof AuthenticatedEsteiraRoute
  '/ideias': typeof AuthenticatedIdeiasRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/priorizacao': typeof AuthenticatedPriorizacaoRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/visao-indicadores': typeof AuthenticatedVisaoIndicadoresRoute
  '/admin/paginas': typeof AuthenticatedAdminPaginasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/backlog/$id': typeof AuthenticatedBacklogIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/backlog': typeof AuthenticatedBacklogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/enriquecimento': typeof AuthenticatedEnriquecimentoRoute
  '/_authenticated/esteira': typeof AuthenticatedEsteiraRoute
  '/_authenticated/ideias': typeof AuthenticatedIdeiasRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/priorizacao': typeof AuthenticatedPriorizacaoRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/_authenticated/visao-indicadores': typeof AuthenticatedVisaoIndicadoresRoute
  '/_authenticated/admin/paginas': typeof AuthenticatedAdminPaginasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/backlog/$id': typeof AuthenticatedBacklogIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/backlog/': typeof AuthenticatedBacklogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/enriquecimento'
    | '/esteira'
    | '/ideias'
    | '/kanban'
    | '/perfil'
    | '/priorizacao'
    | '/roadmap'
    | '/trocar-senha'
    | '/visao-indicadores'
    | '/admin/paginas'
    | '/admin/usuarios'
    | '/backlog/$id'
    | '/admin/'
    | '/backlog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/enriquecimento'
    | '/esteira'
    | '/ideias'
    | '/kanban'
    | '/perfil'
    | '/priorizacao'
    | '/roadmap'
    | '/trocar-senha'
    | '/visao-indicadores'
    | '/admin/paginas'
    | '/admin/usuarios'
    | '/backlog/$id'
    | '/admin'
    | '/backlog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/enriquecimento'
    | '/_authenticated/esteira'
    | '/_authenticated/ideias'
    | '/_authenticated/kanban'
    | '/_authenticated/perfil'
    | '/_authenticated/priorizacao'
    | '/_authenticated/roadmap'
    | '/_authenticated/trocar-senha'
    | '/_authenticated/visao-indicadores'
    | '/_authenticated/admin/paginas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/backlog/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/backlog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enriquecimento': {
      id: '/_authenticated/enriquecimento'
      path: '/enriquecimento'
      fullPath: '/enriquecimento'
      preLoaderRoute: typeof AuthenticatedEnriquecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/esteira': {
      id: '/_authenticated/esteira'
      path: '/esteira'
      fullPath: '/esteira'
      preLoaderRoute: typeof AuthenticatedEsteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ideias': {
      id: '/_authenticated/ideias'
      path: '/ideias'
      fullPath: '/ideias'
      preLoaderRoute: typeof AuthenticatedIdeiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/priorizacao': {
      id: '/_authenticated/priorizacao'
      path: '/priorizacao'
      fullPath: '/priorizacao'
      preLoaderRoute: typeof AuthenticatedPriorizacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocar-senha': {
      id: '/_authenticated/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof AuthenticatedTrocarSenhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visao-indicadores': {
      id: '/_authenticated/visao-indicadores'
      path: '/visao-indicadores'
      fullPath: '/visao-indicadores'
      preLoaderRoute: typeof AuthenticatedVisaoIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/paginas': {
      id: '/_authenticated/admin/paginas'
      path: '/paginas'
      fullPath: '/admin/paginas'
      preLoaderRoute: typeof AuthenticatedAdminPaginasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/backlog/': {
      id: '/_authenticated/backlog/'
      path: '/backlog'
      fullPath: '/backlog/'
      preLoaderRoute: typeof AuthenticatedBacklogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backlog/$id': {
      id: '/_authenticated/backlog/$id'
      path: '/backlog/$id'
      fullPath: '/backlog/$id'
      preLoaderRoute: typeof AuthenticatedBacklogIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminPaginasRoute: typeof AuthenticatedAdminPaginasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminPaginasRoute: AuthenticatedAdminPaginasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnriquecimentoRoute: typeof AuthenticatedEnriquecimentoRoute
  AuthenticatedEsteiraRoute: typeof AuthenticatedEsteiraRoute
  AuthenticatedIdeiasRoute: typeof AuthenticatedIdeiasRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPriorizacaoRoute: typeof AuthenticatedPriorizacaoRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedTrocarSenhaRoute: typeof AuthenticatedTrocarSenhaRoute
  AuthenticatedVisaoIndicadoresRoute: typeof AuthenticatedVisaoIndicadoresRoute
  AuthenticatedBacklogIdRoute: typeof AuthenticatedBacklogIdRoute
  AuthenticatedBacklogIndexRoute: typeof AuthenticatedBacklogIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnriquecimentoRoute: AuthenticatedEnriquecimentoRoute,
  AuthenticatedEsteiraRoute: AuthenticatedEsteiraRoute,
  AuthenticatedIdeiasRoute: AuthenticatedIdeiasRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPriorizacaoRoute: AuthenticatedPriorizacaoRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedTrocarSenhaRoute: AuthenticatedTrocarSenhaRoute,
  AuthenticatedVisaoIndicadoresRoute: AuthenticatedVisaoIndicadoresRoute,
  AuthenticatedBacklogIdRoute: AuthenticatedBacklogIdRoute,
  AuthenticatedBacklogIndexRoute: AuthenticatedBacklogIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
