CREATE TABLE public.prioritization_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  area text CHECK (area IN ('engenharia','dados','ia')),
  position integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.prioritization_items TO authenticated;
GRANT ALL ON public.prioritization_items TO service_role;

ALTER TABLE public.prioritization_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "prioritization_select" ON public.prioritization_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "prioritization_insert" ON public.prioritization_items FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "prioritization_update" ON public.prioritization_items FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "prioritization_delete" ON public.prioritization_items FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'::app_role));

CREATE TRIGGER update_prioritization_items_updated_at
BEFORE UPDATE ON public.prioritization_items
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

INSERT INTO public.prioritization_items (title, position) VALUES
('Automatização lançamento efeitos de contrato',0),
('E-commerce Valori',1),
('Multicaptura v2',2),
('Otimização FinOps Azure',3),
('Gateway de pagamento',4),
('Aplicativo POS Valori',5),
('Fluxo secundario informacional SLC (CERC)',6),
('Backoffice Phoebus V1',7),
('Conciliação Base 1 x Base 2 - Portal Valori',8),
('Portal Valori 2.0',9),
('Projeto Gueno V2 -Conexão SLC',10),
('Melhorias Infraestrutura tecnologia Valori',11),
('Melhorias Link de Pagamento V2',12),
('Otimização FinOps Aws',13),
('Backup bancos homologação microserviços',14),
('Fechamento De Parceiros V2',15),
('HUB - Melhorias',16),
('Construção Processos Valori',17),
('Construção políticas Valori',18),
('Homologação Getnet',19),
('Constução Políticas de CyberSec',20),
('Wazuh/ SIEM',21),
('Data Warehouse',22),
('Projeto IA V2 (Val)',23),
('Orquestrador de execuções valori',24),
('Tap on Phone',25),
('Diligencias ELO',26),
('Aba Estabelecimento/Contato',27),
('Autenticação 2 fatores (2FA)',28),
('Motor de automações',29),
('UI /admin/automations',30),
('Aplicar Política de Gerenciamento de Acessos no Console e Portal',31),
('Backup Veem',32),
('Firewall Clouds',33),
('Implementação de Ferramentas Governança',34),
('SOC',35),
('NPS Portal',36),
('NPS Aplicativo portal Valori',37),
('Mapeamento aplicações Firebase portal',38),
('Healthcheck - Monitoramento de API’s',39),
('Power BI Marketing',40),
('Treinamentos CyberSec',41),
('Dataset de treino com labels de fraude/ chargeback',42),
('Modelar métricas core de pagamentos',43),
('Modelo de scoring near-real-time com latência alvo',44),
('Padronizar camadas e convenções (bronze/ silver/gold)',45),
('Aplicativo Valori V2',46),
('Automatização Liquidação PIX',47),
('Conciliação Extrato PIX via API',48),
('Disponibilização API BAAS',49),
('Portal Valori - Menu de adm perfis de usuários',50),
('Precificador Valori - V3',51),
('Reprocessamento de transações V2',52),
('Construção matriz de risco de acessos',53),
('Processo de armazenamento e avalição de cloud',54),
('Processo de registro de eventos e falhas',55),
('Aba ''Meus atendimentos''',56),
('Consultar agenda 365 via CRM',57),
('Fazer um invite e sincronizar com 365',58),
('IAs especializadas por função',59),
('Incrementar campos do CRM',60),
('Reduzir tempo + indicador ''digitando''',61),
('Sincronização Agenda 365',62),
('FGTS Pay',63),
('Area de dashboards portal valori',64),
('Front consulta Chargeback EDI',65),
('Portal Valori - Criar front de consulta EDI Rede',66),
('Portal Valori - Front EDI ADIQ - Ajuste',67),
('Modelo de propensão a churn de merchants',68),
('Débito Ténico: Identificação de Tipo de Cobrança no PDV - Recorrente ou Evento',69),
('Painel de Cancelamento V3 - Melhorias',70),
('Portal - Empresas - Inclusão conta liquidação para parceiros e comerciais',71),
('Projeto Geolocalização de POS via MDM',72),
('Projeto adiantamento de salário',73),
('API Integração Google Calendario',74),
('Assistente de IA interno',75),
('Duplicar agentes de IA',76),
('IA analisar áudio e imagem',77),
('Integração com Instagram',78),
('Webhook genérico',79),
('Parceria - Clinica Vittá',80),
('Parceria Meep',81),
('Projeto Conciliadora',82),
('Projeto Saga',83),
('Seguro Valori',84),
('Solução Bluetech Azo - Trinus',85),
('Valori IP',86);